"""Fix Address ORM model

Revision ID: 1296f1e73ab1
Revises: d660eb36fee3
Create Date: 2022-06-08 18:29:24.928352

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1296f1e73ab1"
down_revision = "d660eb36fee3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "address", sa.Column("address_line_1", sa.String(length=100), nullable=True)
    )
    op.add_column("address", sa.Column("city", sa.String(length=30), nullable=True))
    op.add_column("address", sa.Column("country", sa.String(length=30), nullable=True))
    op.add_column(
        "vehicle", sa.Column("image_path", sa.String(length=200), nullable=True)
    )
    op.drop_constraint("vehicle_vehicle_type_id_fkey", "vehicle", type_="foreignkey")
    op.create_foreign_key(None, "vehicle", "vehicle_type", ["vehicle_type_id"], ["id"])
    op.drop_column("vehicle", "truck_model_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vehicle",
        sa.Column("truck_model_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "vehicle", type_="foreignkey")
    op.create_foreign_key(
        "vehicle_vehicle_type_id_fkey", "vehicle", "user", ["vehicle_type_id"], ["id"]
    )
    op.drop_column("vehicle", "image_path")
    op.drop_column("address", "country")
    op.drop_column("address", "city")
    op.drop_column("address", "address_line_1")
    # ### end Alembic commands ###
