"""Delete truck model relationship

Revision ID: b108ed1a98f2
Revises: 5054790e7997
Create Date: 2022-06-08 14:08:55.379792

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b108ed1a98f2"
down_revision = "5054790e7997"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vehicle", sa.Column("model_name", sa.String(length=100), nullable=False)
    )
    op.add_column("vehicle", sa.Column("vehicle_type_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "vehicle", "user", ["vehicle_type_id"], ["id"])
    op.drop_column("vehicle", "name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vehicle",
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "vehicle", type_="foreignkey")
    op.drop_column("vehicle", "vehicle_type_id")
    op.drop_column("vehicle", "model_name")
    # ### end Alembic commands ###
