"""Delete truck model

Revision ID: d660eb36fee3
Revises: b108ed1a98f2
Create Date: 2022-06-08 14:10:58.663901

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d660eb36fee3"
down_revision = "b108ed1a98f2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    ...
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("truck_model")
    op.drop_constraint("vehicle_truck_model_id_fkey", "vehicle", type_="foreignkey")
    op.drop_column("vehicle", "truck_model_id")
    op.add_column(
        "vehicle",
        sa.Column("truck_model_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "vehicle_truck_model_id_fkey",
        "vehicle",
        "truck_model",
        ["truck_model_id"],
        ["id"],
    )
    op.create_table(
        "truck_model",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("vehicle_type_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["vehicle_type_id"],
            ["vehicle_type.id"],
            name="truck_model_vehicle_type_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="truck_model_pkey"),
    )
    # ### end Alembic commands ###
