from gateways.database.ORM.base_class import Base
from gateways.database.ORM.address import AddressORM
from gateways.database.ORM.load import LoadORM
from gateways.database.ORM.user import UserORM
from gateways.database.ORM.transport_company import TransportCompanyORM
from gateways.database.ORM.vehicle_type import VehicleTypeORM
from gateways.database.ORM.contact import ContactORM
from gateways.database.ORM.generator import GeneratorORM
from gateways.database.ORM.vehicle import VehicleORM
from gateways.database.ORM.subscription import SubscriptionORM
from gateways.database.ORM.subscription_plan import SubscriptionPlanORM
